name: Build, Test and Deploy the application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install node modules
      run: npm install
    - name: Starting the BackEnd
      run: npm run server &
    - name: Starting the FrontEnd
      run: npm run start &
    - name: Installing Playwright Browsers
      run: npx playwright install
    - name: Running PlayWright UI tests
      run: npm run test
      
  deploy_be:
    needs: build_test
    if: github.ref == 'refs/ehads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to render
        uses: JorgeLNJunior/render-deploy@v1.4.7
        with:
          service_id: ${{ secrets.BE_SERVICE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true

  deploy_fe:
    needs: deploy_be
    if: github.ref == 'refs/ehads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to render
        uses: JorgeLNJunior/render-deploy@v1.4.7
        with:
          service_id: ${{ secrets.FE_SERVICE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true